[package]
name = "orgflow"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"

[dependencies.uuid]
version = "1.16.0"
# Lets you generate random UUIDs
features = ["v4"]

[[bin]]
name = "orgflow"
path = "src/main.rs"

[lib]
name = "orgflow"
path = "src/lib/mod.rs"
